config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }

  namespace :admin do
    root to: 'homes#top'
    resources :posts, only: [:show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :events, only: [:new, :create, :index, :edit, :update, :destroy]
    resources :tags, only: [:index, :create, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update] do
      get 'following' => 'users#following', as: 'following'
      get 'follower' => 'users#follower', as: 'follower'
    end
  end

  devise_for :users, path: "users", controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    # omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'

    resources :posts, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :events, only: [:new, :create, :index]

    resources :records, only: [:new, :create, :show, :destroy]
    patch '/update_record' => 'records#update_record'
    delete '/delete_record' => 'records#delete_record'

    resources :training_records

    resources :users
    get 'search' => 'users#search'
    get '/:username/unsubscribe' => 'users#unsubscribe'
    patch '/:username/widthdraw' => 'users#widthdraw', as: "users_widthdraw"
    resources :relationships, only: [:create, :destroy]

    # 以下のルーティングは常に一番下に
    get '/mypage' => 'users#mypage'
    get '/:username' => 'users#show'
    get '/:username/edit' => 'users#edit'
    get '/:username/following' => 'users#following', as: 'following'
    get '/:username/follower' => 'users#follower', as: 'follower'
    patch '/:username' => 'users#update'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def total_weight(sub)
    (sub.weight * sub.rep / 40) + sub.weight
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :genre
  validates :name, presence: true, uniqueness: true
  paginates_per 6
end

app/models/event_datum.rb
class EventDatum < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :events, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image

  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :body, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_many :training_records, inverse_of: :record, dependent: :destroy
  accepts_nested_attributes_for :training_records, allow_destroy: true

  validates :comment, presence: true
  validates :start_time, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/set_event.rb
class SetEvent < ApplicationRecord
  belongs_to :training_record

  def max
    (self.weight * self.rep / 40 + weight).round
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :user_tags
  has_many :users, through: :user_tags
end

app/models/training_record.rb
class TrainingRecord < ApplicationRecord
  belongs_to :record
  has_many :set_events, dependent: :destroy
  accepts_nested_attributes_for :set_events, allow_destroy: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  validates :name, presence: true
  validates :email, uniqueness: true, presence: true
  validates :is_active, inclusion: { in: [true, false] }

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :records, dependent: :destroy
  has_many :user_tags
  has_many :tags, through: :user_tags

  # フォローする
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed

  # フォローされる
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # def self.search(keyword)
  #   where(["name like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
  # end

  def self.search(search)
    if search
      User.where(['name LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end

end

app/models/user_tag.rb
class UserTag < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save
    redirect_to admin_events_path
  end

  def index
    @event1 = Event.where(genre_id: 1).page(params[:page])
    @event2 = Event.where(genre_id: 2).page(params[:page])
    @event3 = Event.where(genre_id: 3).page(params[:page])
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(update_event_params)
    redirect_to admin_events_path
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to admin_events_path
  end

  private

  def event_params
    params.require(:event).permit(:genre_id, :name)
  end

  def update_event_params
    params.require(:event).permit(:genre_id, :name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/events/edit.html.erb
<div class="container users-title">
   <div class="row">
     <div class="col-12">
       <h1 class="page-title collapse2">Event Edit</h1>
     </div>
   </div>
   <div class="row">
     <div class="col-12">
       <p class="page-title-translate collapse3">種目編集</p>
     </div>
   </div>
 </div>

<div class="container mt-10">
<%= form_with model: [:admin, @event], local:true do |f| %>
  <div class="record__new">
    <div class="form-group">
      <%= f.label 'カテゴリー', class: "ccontrol-label" %><br />
      <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: '-- 選択して下さい --', class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label '種目名', class: "control-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
    <div>
       <%= f.submit '編集する', class: "btn btn-success" %>
       <%= link_to '削除する', admin_event_path(@event), method: :delete, class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/admin/events/index.html.erb
<div class="container users-title">
   <div class="row">
     <div class="col-12">
       <h1 class="page-title collapse2">Events</h1>
     </div>
   </div>
   <div class="row">
     <div class="col-12">
       <p class="page-title-translate collapse3">種目一覧</p>
     </div>
   </div>
 </div>

<h2></h2>

<div class="events">


 <div class="card">
 <div class="card-header">
  <%= link_to new_admin_event_path do %>
   <i class="fas fa-plus-circle fa-2x fa-pull-right"></i>
  <% end %>
 </div>
  <div id="event_lists">
   <div class="card-header">
    <%= link_to '上半身', admin_genres_path %>&emsp; &emsp;
    <%= link_to_next_page @event1, 'もっと見る', remote: true, id: 'view_more' %>
   </div>
   <ul class="list-group list-group-flush">
    <%= render partial: 'public/events/form_event1' %>
   </ul>
  </div>
 </div>


 <div class="card">
  <div id="event__lists">
   <div class="card-header">
    <%= link_to '下半身', admin_genres_path %>&emsp; &emsp;
    <%= link_to_next_page @event2, 'もっと見る', remote: true, id: 'view__more' %>
   </div>
   <ul class="list-group list-group-flush">
    <%= render partial: 'public/events/form_event2' %>
   </ul>
  </div>
 </div>


 <div class="card">
  <div id="event_lists">
   <div class="card-header">
    <%= link_to '体幹', admin_genres_path %>&emsp; &emsp;
    <%= link_to_next_page @event3, 'もっと見る', remote: true, id: 'view_more' %>
   </div>
   <ul class="list-group list-group-flush">
    <%= render partial: 'public/events/form_event3' %>
   </ul>
  </div>
 </div>

</div>

app/views/admin/events/index.js.erb
$('#event_lists').append("<%= escape_javascript(render 'public/events/form_event1', object: @event1) %>");
$("#view_more").replaceWith("<%= escape_javascript(
link_to_next_page(@event1, 'もっと見る', remote: true, id: 'view_more')) %>");

$('#event__lists').append("<%= escape_javascript(render 'public/events/form_event2', object: @event2) %>");
$("#view__more").replaceWith("<%= escape_javascript(
link_to_next_page(@event2, 'もっと見る', remote: true, id: 'view__more')) %>");

$('#event_lists').append("<%= escape_javascript(render 'public/events/form_event3', object: @event3) %>");
$("#view_more").replaceWith("<%= escape_javascript(
link_to_next_page(@event3, 'もっと見る', remote: true, id: 'view_more')) %>");

app/views/admin/events/new.html.erb
<div class="container users-title">
   <div class="row">
     <div class="col-12">
       <h1 class="page-title collapse2">Event</h1>
     </div>
   </div>
   <div class="row">
     <div class="col-12">
       <p class="page-title-translate collapse3">種目登録</p>
     </div>
   </div>
 </div>

<div class="container mt-10">
<%= form_with model: [:admin, @event], local:true do |f| %>
  <div class="record__new">
    <div class="form-group">
      <%= f.label 'カテゴリー', class: "ccontrol-label" %><br />
      <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: '-- 選択して下さい --', class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label '種目名', class: "control-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
    <div class="text-center">
       <%= f.submit '登録する', class: "btn btn-success w-25" %>
    </div>
  <% end %>
</div>