config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }

  namespace :admin do
    root to: 'homes#top'
    resources :posts, only: [:show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :events, only: [:new, :create, :index, :edit, :update, :destroy]
    resources :tags, only: [:index, :create, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update] do
      get 'following' => 'users#following', as: 'following'
      get 'follower' => 'users#follower', as: 'follower'
    end
  end

  devise_for :users, path: "users", controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    # omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'

    resources :posts, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :events, only: [:new, :create, :index]

    resources :records, only: [:new, :create, :show, :destroy]
    patch '/update_record' => 'records#update_record'
    delete '/delete_record' => 'records#delete_record'

    resources :training_records

    resources :users
    get 'search' => 'users#search'
    get '/:username/unsubscribe' => 'users#unsubscribe'
    patch '/:username/widthdraw' => 'users#widthdraw', as: "users_widthdraw"
    resources :relationships, only: [:create, :destroy]

    # 以下のルーティングは常に一番下に
    get '/mypage' => 'users#mypage'
    get '/:username' => 'users#show'
    get '/:username/edit' => 'users#edit'
    get '/:username/following' => 'users#following', as: 'following'
    get '/:username/follower' => 'users#follower', as: 'follower'
    patch '/:username' => 'users#update'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def total_weight(sub)
    (sub.weight * sub.rep / 40) + sub.weight
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :genre
  validates :name, presence: true, uniqueness: true
  paginates_per 6
end

app/models/event_datum.rb
class EventDatum < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :events, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image

  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :body, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_many :training_records, inverse_of: :record, dependent: :destroy
  accepts_nested_attributes_for :training_records, allow_destroy: true

  validates :comment, presence: true
  validates :start_time, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/set_event.rb
class SetEvent < ApplicationRecord
  belongs_to :training_record

  def max
    (self.weight * self.rep / 40 + weight).round
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :user_tags
  has_many :users, through: :user_tags
end

app/models/training_record.rb
class TrainingRecord < ApplicationRecord
  belongs_to :record
  has_many :set_events, dependent: :destroy
  accepts_nested_attributes_for :set_events, allow_destroy: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  validates :name, presence: true
  validates :email, uniqueness: true, presence: true
  validates :is_active, inclusion: { in: [true, false] }

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :records, dependent: :destroy
  has_many :user_tags
  has_many :tags, through: :user_tags

  # フォローする
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed

  # フォローされる
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # def self.search(keyword)
  #   where(["name like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
  # end

  def self.search(search)
    if search
      User.where(['name LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end

end

app/models/user_tag.rb
class UserTag < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @post_comments = @post.post_comments.includes(:user)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(update_post_params)
    redirect_to admin_post_path(@post)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_root_path
  end

  private

  def update_post_params
    params.require(:post).permit(:body, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/edit.html.erb
<div class="container users-title">
  <div class="row">
    <div class="col-12">
      <h1 class="page-title collapse2">Edit Post</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p class="page-title-translate collapse3">投稿編集</p>
    </div>
  </div>
</div>

<%= form_with model: [:admin, @post], local:true do |f| %>
<div class="card__post card">
  <div class="card-body">
    <div class="card-title mb-5">
      <%= f.attachment_field :image, class: "form-control-file" %>
    </div>
    <div class="card-subtitle mb-5">
       <%= f.label '投稿内容' %>
        <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="mt-3">
      <%= f.submit '変更を保存', class: "btn btn-success mr-3" %>
      <%= link_to '削除する', admin_post_path(@post), method: :delete, class: "btn btn-danger" %>
    </div>
  </div>
  <% end %>

app/views/admin/posts/show.html.erb
<div class="container users-title">
  <div class="row">
    <div class="col-12">
      <h1 class="page-title collapse2">Post</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p class="page-title-translate collapse3"><%= @post.user.name %>さんの投稿</p>
    </div>
  </div>
</div>

<div class="card__posts card">
  <%= attachment_image_tag @post, :image, fallcack: "no_image.jpg", class: "card-img-top" %>
  <div class="card-body">
    <p class="card-title">
      <%= @post.body %>
    </p>
    <h4 class="card-subtitle text-muted">
      <ul class="post-details">
        <li>By <%= @post.user.name %></li>
        <li>
          <i class="fas fa-heart" style="color: crimson;"></i><%= @post.favorites.count %> いいね
         </li>
        <li><i class="far fa-comment-dots"></i>
          <%= link_to "#{@post.post_comments.count}コメント", admin_post_path(@post.id) %>
        </li>
        <li><i class="far fa-clock"></i> <%= @post.created_at.strftime('%Y/%m/%d') %></li>
        <li><%= link_to '編集', edit_admin_post_path(@post), class: "btn btn-primary btn-sm" %></li>
      </ul>
    </h4>
  </div>

  <div class="post-comment mt-5">
    <% @post.post_comments.each do |post_comment| %>
    <table class="table table-hover ">
      <tr>
        <th>
          <img src="<%= post_comment.user.profile_image %>"> <%= post_comment.user.name %>
        </th>
        <th class="text-center"><%= post_comment.comment %></th>
        <th class="text-right">
          <%= link_to "削除", admin_post_post_comment_path(post_comment.post, post_comment), method: :delete, class: "btn btn-danger" %>
        </th>
      </tr>
    </table>
    <% end %>
  </div>
</div>