config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }

  namespace :admin do
    root to: 'homes#top'
    resources :posts, only: [:show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :events, only: [:new, :create, :index, :edit, :update, :destroy]
    resources :tags, only: [:index, :create, :edit, :update]
    resources :users, only: [:index, :show, :edit, :update] do
      get 'following' => 'users#following', as: 'following'
      get 'follower' => 'users#follower', as: 'follower'
    end
  end

  devise_for :users, path: "users", controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    # omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'

    resources :posts, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :events, only: [:new, :create, :index]

    resources :records, only: [:new, :create, :show, :destroy]
    patch '/update_record' => 'records#update_record'
    delete '/delete_record' => 'records#delete_record'

    resources :training_records

    resources :users
    get 'search' => 'users#search'
    get '/:username/unsubscribe' => 'users#unsubscribe'
    patch '/:username/widthdraw' => 'users#widthdraw', as: "users_widthdraw"
    resources :relationships, only: [:create, :destroy]

    # 以下のルーティングは常に一番下に
    get '/mypage' => 'users#mypage'
    get '/:username' => 'users#show'
    get '/:username/edit' => 'users#edit'
    get '/:username/following' => 'users#following', as: 'following'
    get '/:username/follower' => 'users#follower', as: 'follower'
    patch '/:username' => 'users#update'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  validates :name, presence: true
  validates :email, uniqueness: true, presence: true
  validates :is_active, inclusion: { in: [true, false] }

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :records, dependent: :destroy
  has_many :user_tags
  has_many :tags, through: :user_tags

  # フォローする
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed

  # フォローされる
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # def self.search(keyword)
  #   where(["name like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
  # end

  def self.search(search)
    if search
      User.where(['name LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.order(created_at: :asc).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @tags = @user.tags.find_by(id: @tag_id)
    @posts = Post.where(user_id: @user.id)
    @all_records = Record.includes(:user)
    # @user = User.find_by(id: @user_id)
    @records = Record.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
    @tags = @user.tags.find_by(id: @tag_id)
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_users_path
  end

  def following
    @title = "Following"
    @user = User.find(params[:user_id])
    @users = @user.following
    render 'show_following'
  end

  def follower
    @title = "Followers"
    @user = User.find(params[:user_id])
    @users = @user.followers
    render 'show_follower'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :is_active)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # def twitter
  #   callback_from :twitter
  # end

  # private

  # def callback_from(provider)
  #   provider = provider.to_s

  #   @user = User.find_for_oauth(request.env['omniauth.auth'])

  #   if @user.persisted?
  #     flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
  #     sign_in_and_redirect @user, event: :authentication
  #   else
  #     session["devise.#{provider}_data"] = request.env['omniauth.auth']
  #     redirect_to new_user_registration_url
  #   end
  # end

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false)
        flash[:error] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container users-title">
  <div class="row">
    <div class="col-12">
      <h1 class="page-title">Edit</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p class="page-title-translate">登録情報編集</p>
    </div>
  </div>
</div>


<%= form_with model: [:admin, @user], local:true do |f| %>
<div class="container">
  <div class="row profile__edit">
    <div class="col">
      <div class="form-group">
        <%= f.label 'プロフィール画像', class: "exampleFormControlFile1" %>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "form-control-file" %>
      </div>

      <div class="form-group">
        <%= f.label :tag_ids, "タグ機能" %><br/>
        <span>
          <% Tag.all.each do |tag| %>
            <%= f.check_box :tag_ids, { multiple: true, checked: @user.tags.find_by(id: tag.id).present?, include_hidden: false } ,tag[:id] %>
            <label class="form^check-label">
              <%= tag.name %>
            </label>
          <% end %>
        </span>
      </div>

      <div class="form-group">
        <%= f.label 'Name' %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label 'E-mail' %>
        <%= f.text_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label 'About' %>
        <%= f.text_area :introduction, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label 'ステータス' %>
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, :false, class: "form-check-input" %>
          <%= f.label :is_active, "有効", value: :false, class: "form-check-label" %>
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_active, :true, class: "form-check-input" %>
          <%= f.label :is_active, "退会", value: :true, class: "form-check-label" %>
        </div>
      </div>

      <div class="profile__edit--btn">
        <%= f.submit '変更を保存', class: "btn btn-success mb-2 w-25" %>
      </div>

    </div>
  </div>
</div>
<% end %>

app/views/admin/users/index.html.erb
<div class="container users-title">
  <div class="row">
    <div class="col-12">
      <h1 class="page-title collapse2 animate__animated animate__bounceInDown">Users</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p class="page-title-translate collapse3 animate__animated animate__backInRight">会員一覧</p>
    </div>
  </div>
</div>

<div class="admin--users">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">会員ID</th>
        <th scope="col">ユーザー名</th>
        <th scope="col">メールアドレス</th>
        <th scope="col">ステータス</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td scope="row"><%= user.id %></td>
        <td>
          <%= link_to admin_user_path(user.id) do %>
            <%= user.name %>
          <% end %>
        </td>
        <td><%= user.email %></td>
        <td>
        <% if user.is_active == false %>
          <p class="text-success">有効</p>
        <% elsif user.is_active == true %>
          <p class="text-danger">退会</p>
        <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <div class="text-center"><%= paginate @users %></div>
</div>

app/views/admin/users/show.html.erb
<div class="row py-5 px-4">
    <div class="col-md-5 mx-auto">
        <div class="bg-white shadow rounded overflow-hidden">
            <div class="px-4 pt-0 pb-4 cover">
                <div class="media align-items-end profile-head">
                    <div class="profile mr-3 mt-3">
                      <%= attachment_image_tag @user, :profile_image, fallback: "no_image.png", size: "130x85", class: "rounded mb-2 img-thumbnail" %>
                      <p class="profile__name"><%= @user.name %></p>
                        <%= link_to "プロフィール編集", edit_admin_user_path(@user), class: "btn btn-outline-dark btn-sm btn-block" %>
                    </div>
                    <div class="media-body mb-5 text-white">
                        <h4 class="mt-0 mb-0"><%= @user.name %></h4>
                        <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2">
                          <% @user.tags.each do |tag| %>
                            <%= tag.name %>
                          <% end %>
                        </i>
                        </p>
                    </div>
                </div>
            </div>
            <div class="bg-light p-4 d-flex justify-content-end text-center">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item">
                        <h5 class="font-weight-bold mb-0 d-block">
                          <%= @user.posts.count %>
                        </h5><small class="text-muted"> <i class="fas fa-image mr-1"></i>Posts</small>
                    </li>
                    <li class="list-inline-item">
                        <h5 class="font-weight-bold mb-0 d-block">
                          <%= link_to admin_user_follower_path(@user) do %>
                            <%= @user.followers.count %>
                          <% end %>
                        </h5><small class="text-muted"> <i class="fas fa-user mr-1"></i>Followers</small>
                    </li>
                    <li class="list-inline-item">
                        <h5 class="font-weight-bold mb-0 d-block">
                          <%= link_to admin_user_following_path(@user) do %>
                            <%= @user.following.count %>
                          <% end %>
                        </h5><small class="text-muted"> <i class="fas fa-user mr-1"></i>Following</small>
                    </li>
                </ul>
            </div>
            <div class="px-4 py-3">
                <h5 class="mb-0">About</h5>
                <div class="p-4 rounded shadow-sm bg-light">
                    <p class="font-italic mb-0"><%= @user.introduction %></p>
                </div>
            </div>
        </div>
    </div>
</div>

<ul class="profile__nav nav nav-tabs mb-3">
  <li class="nav-item">
    <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Posts</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">Records</a>
  </li>
</ul>
<div class="tab-content" id="pills-tabContent">
  <div class="profile__posts tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
    <%=render partial: "public/posts/posts" %>
  </div>
  <div class="profile__calender tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">
      <%= month_calendar events: @user.records do |date, records| %>
          <%= date.day %>
          <% records.each do |record| %>
            <%= link_to record_path(record) do %>
              <%= record.comment %>
            <% end %>
          <% end %>
    <% end %>
  </div>
</div>

app/views/admin/users/show_follower.html.erb
<div class="container users-title">
   <div class="row">
     <div class="col-12">
       <h1 class="page-title collapse2">Followers</h1>
     </div>
   </div>
   <div class="row">
     <div class="col-12">
       <p class="page-title-translate collapse3">フォロワー</p>
     </div>
   </div>
 </div>


<div class="user__follow my-3 p-3 bg-white rounded shadow-sm">
  <div class="media text-muted pt-3">
  <% if @users.any? %>
    <% @users.each do |user| %>
      <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg",width: "48", height: "48", class: "mr-2 rounded" %>
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark">
            <%= link_to "/#{user.name}" do %>
              <%= user.name %>
            <% end %>
          </strong>
        </div>
        <span class="d-block">
          <%= link_to admin_user_path(user) do %>
            <%= user.posts.count %> Post
          <% end %>
          <%= link_to admin_user_follower_path(user) do %>
            <%= user.followers.count %> Follower
          <% end %>
          <%= link_to admin_user_following_path(user) do %>
            <%= user.following.count %> Following
          <% end %>
        </span>
        <span class="d-block">
          <%= user.introduction %>
        </span>
      </div>
    <% end %>
  <% end %>
  </div>

app/views/admin/users/show_following.html.erb
<div class="container users-title">
   <div class="row">
     <div class="col-12">
       <h1 class="page-title collapse2">Followings</h1>
     </div>
   </div>
   <div class="row">
     <div class="col-12">
       <p class="page-title-translate collapse3">フォロー</p>
     </div>
   </div>
 </div>

<div class="user__follow my-3 p-3 bg-white rounded shadow-sm">
  <div class="media text-muted pt-3">
  <% if @users.any? %>
    <% @users.each do |user| %>
      <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg",width: "48", height: "48", class: "mr-2 rounded" %>
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark">
            <%= link_to "/#{user.name}" do %>
              <%= user.name %>
            <% end %>
          </strong>
        </div>
        <span class="d-block">
          <%= link_to admin_user_path(user) do %>
            <%= user.posts.count %> Post
          <% end %>
          <%= link_to admin_user_follower_path(user) do %>
            <%= user.followers.count %> Follower
          <% end %>
          <%= link_to admin_user_following_path(user) do %>
            <%= user.following.count %> Following
          <% end %>
        </span>
        <span class="d-block">
          <%= user.introduction %>
        </span>
      </div>
    <% end %>
  <% end %>
  </div>